# Railway configuration scoped to the backend service
# This file must live inside the service root (brain/) so Railway picks it up.

[build]
root = "."  # build context is already brain/, so keep dot

[deploy]
watchPaths = ["./**"]  # redeploy only on changes inside brain

[service]
# Expose an HTTP/WebSocket endpoint so Railway keeps the container alive
# and routes traffic correctly. Use the port provided in $PORT.
    type = "web"
startCommand = "tsx -r dotenv/config src/index.ts"